'use strict';

/**
 * TicketComment Model - Ticketing Module
 * 
 * Comments and activity log for tickets
 * 
 * @module modules/ticketing/models/ticketComment
 */

module.exports = (sequelize, DataTypes) => {
  const TicketComment = sequelize.define('TicketComment', {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true
    },
    tenantId: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: 'Tenants',
        key: 'id'
      },
      onUpdate: 'CASCADE',
      onDelete: 'CASCADE'
    },
    ticketId: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: 'Tickets',
        key: 'id'
      },
      onUpdate: 'CASCADE',
      onDelete: 'CASCADE'
    },
    userId: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: 'Users',
        key: 'id'
      },
      onUpdate: 'CASCADE',
      onDelete: 'RESTRICT',
      comment: 'User who created the comment'
    },
    comment: {
      type: DataTypes.TEXT,
      allowNull: false,
      comment: 'Comment content'
    },
    isInternal: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: false,
      comment: 'Internal note (visible only to staff)'
    },
    isSystemGenerated: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: false,
      comment: 'Auto-generated by system (status changes, assignments, etc.)'
    }
  }, {
    tableName: 'TicketComments',
    timestamps: true,
    paranoid: true,
    indexes: [
      {
        fields: ['tenantId']
      },
      {
        fields: ['ticketId']
      },
      {
        fields: ['userId']
      },
      {
        fields: ['createdAt']
      },
      {
        fields: ['isInternal']
      }
    ]
  });

  // Associations
  TicketComment.associate = function(models) {
    TicketComment.belongsTo(models.Tenant, {
      foreignKey: 'tenantId',
      as: 'tenant'
    });

    TicketComment.belongsTo(models.Ticket, {
      foreignKey: 'ticketId',
      as: 'ticket'
    });

    TicketComment.belongsTo(models.User, {
      foreignKey: 'userId',
      as: 'user'
    });
  };

  return TicketComment;
};
